export const LOAD_DATA = 'LOAD_DATA';
export const FETCH_DATA = 'FETCH_DATA';
export const DELETE_SIGNATURE = 'DELETE_SIGNATURE';
export const DELETE_REMOVAL_SIGNATURE = 'DELETE_REMOVAL_SIGNATURE';
export const ADD_REMOVAL_SIGNATURE = 'ADD_REMOVAL_SIGNATURE';
export const REMOVE_REMOVAL_SIGNATURE = 'REMOVE_REMOVAL_SIGNATURE';
